HEADERS = {
    'authority': 'c.timewatch.co.il',
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'origin': 'https://c.timewatch.co.il',
    'referer': '',
}

DATA = {
    'e': '',
    'tl': '',
    'c': '',
    'd': '',
    'csrf_token': '',
    'nextdate': '',
    'emm0': '',
    'ehh0': '',
    'xmm0': '',
    'xhh0': '',
    'task0': '0',
    'taskdescr0': '',
    'what0': '1',
    'emm1': '',
    'ehh1': '',
    'xmm1': '',
    'xhh1': '',
    'task1': '0',
    'taskdescr1': '',
    'what1': '1',
    'emm2': '',
    'ehh2': '',
    'xmm2': '',
    'xhh2': '',
    'task2': '0',
    'taskdescr2': '',
    'what2': '1',
    'emm3': '',
    'ehh3': '',
    'xmm3': '',
    'xhh3': '',
    'task3': '0',
    'taskdescr3': '',
    'what3': '1',
    'emm4': '',
    'ehh4': '',
    'xmm4': '',
    'xhh4': '',
    'task4': '0',
    'taskdescr4': '',
    'what4': '1',
    'excuse': '0',
    'teken': '',
    'remark': '',
}
